# Generated by Django 5.0.6 on 2024-06-16 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jjapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="class_teacher",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="recorded_at",
        ),
        migrations.AddField(
            model_name="attendance",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="jjapp.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jjapp.student"
            ),
        ),
    ]
