# Generated by Django 5.0.6 on 2024-06-16 10:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jjapp", "0002_remove_attendance_class_teacher_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="recorded_by",
        ),
        migrations.AddField(
            model_name="attendance",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_attendances",
                to="jjapp.teacher",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="recorded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="jjapp.student",
            ),
        ),
    ]
