# Generated by Django 5.0.6 on 2024-06-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jjapp", "0003_remove_attendance_recorded_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="roll_number",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
